### ISSUE TITLE
ScrollView Instrumentation breaks the component

### ISSUE THREAD

**Issue by cesarp** [heap/react-native-heap#119]
When I enabled auto tracking in my application with the babel plugin using @heap/react-native-heap 0.6.0 and react-native 0.60.4 the ScrollView component crashes when the  `onMomentumScrollEnd` callback gets executed.

It throws an exception saying `_this is not defined` which by the way is correct, it isn't defined on that scope where it is trying to get access to it.

gist with the generated code that crashes the app:
https://gist.github.com/cesarp/92ed29d7035a0a9551fc7893aa3f1fd3#file-scrollview-js-L464

My system configuration:

```
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 706.92 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 25.0.1, 25.0.2, 26.0.2, 26.0.3, 27.0.3, 28.0.1, 28.0.3
      System Images: android-26 | Google APIs Intel x86 Atom_64, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4
```

**Comment by daviscabral** [comment]
Same here.

**Comment by jnatkins** [comment]
Hi @cesarp and @daviscabral, wanted to give a heads up that our eng team is looking into this, and will update with more details.

Thanks!

**Comment by jnatkins** [comment]
@cesarp @daviscabral As a heads up, we've fixed this issue. We plan to release a 0.7.0 in the next week or so, but in the meantime, if you want to test it out, you can build your app off of our develop branch.

Thanks!
