### ISSUE TITLE
Target accessibilityLabel is capturing all text in the screen

### ISSUE THREAD

**Issue by bruno-campos** [heap/react-native-heap#137]
The RCTTouchHandler on RCTRootContentView event is capturing everything that is on the screen. That can lead to PII mistakenly going into Heap and I see no way of disabling that. 

![image](https://user-images.githubusercontent.com/926303/64053472-e6b9af00-cb58-11e9-87f6-8abd943da05e.png)

Tested with 0.8.0. This was also happening at 0.3.0

**Comment by kevinlr5** [comment]
Thanks for filing this issue! We're a bit short on resources to code on this this week, but we'll look into it next week and get back to you.

**Comment by bruno-campos** [comment]
Thank you Kevin!

**Comment by bruno-campos** [comment]
@kevinlr5 any updates on this?

**Comment by jmtaber129** [comment]
Hi Bruno!  Thanks for flagging this (especially as a potential PII issue).  I’ve looked into this, and while we don’t currently have a way to correct this through the react-native-heap SDK, you can use the [native Heap iOS SDK’s `heapIgnore` functionality](https://docs.heap.io/docs/ios#section-sensitive-data) to suppress native events (`RCTTouchHandler`s, etc.) coming from your react native app.  You can do this by adding the following line to the `didFinishLaunchingWithOptions` function in your `AppDelegate.m` file:
```
[rootView setValue:@true forKey:@"heapIgnore"];
```
Check out https://github.com/heap/react-native-heap/pull/144 to get a better idea of where this would go in our test app.

We’ll also be updating our docs with these instructions.

(Note: this will suppress _all_ native iOS events within the root view of the react native app, not just remove the Target accessibilityLabel you mentioned could contain PII.  These native iOS events are usually meaningless in React Native apps, but if this isn’t the case for you, and some of these events are useful, please reopen this issue so our team can revisit this).
