### ISSUE TITLE
Typings not available in NPM

### ISSUE THREAD

**Issue by natethebosch** [heap/react-native-heap#14]
I see that you've got an index.d.ts in the develop branch, but it's not in master. Is that going to be merged over at some point?

**Comment by drob** [comment]
Whoops, attempted to do so but missed the package.json entry. Thanks for flagging this. We'll get it fixed right away.

**Comment by drob** [comment]
There's a new version on npm that should fix this. Try with 0.1.2?

**Comment by natethebosch** [comment]
Great, thanks!
