### ISSUE TITLE
Expo support

### ISSUE THREAD

**Issue by calebdre** [heap/react-native-heap#145]
Would love to try out Heap but we have an expo project and cannot `link` our project

**Comment by jmtaber129** [comment]
Hi Caleb!  The React Native Heap SDK depends on the native iOS/Android Heap libraries, but managed expo projects (projects that use the expo-cli and expo client app) don't support custom native code (including third-party native libraries), so Heap is currently unsupported on managed expo apps.

To use Heap, you'll need to permanently `expo eject` your expo project to a vanilla React Native project.
