### ISSUE TITLE
Android manual tracking doesn't work (Heap.track())

### ISSUE THREAD

**Issue by lochness42** [heap/react-native-heap#165]
I've been trying to use Manual tracking as per (https://docs.heap.io/docs/react-native#section-manual-tracking-usage-examples) and while everything works perfectly on iOS, I've hit a problem on Android.
Everything works as long as I don't include 
`Heap.track('signed-up', { isPaid: true, amount: 20 });`

I end up with red screen right away:
![Screenshot_1576224905](https://user-images.githubusercontent.com/3199980/70783917-3f682d00-1d81-11ea-8608-eb6c4454baf3.png)

Do you have any suggestion how to get this working? I can see events when I query for them including set user properties and identifier so I assume that I've got everything correctly linked on Android.

**Comment by GrandPoohBear** [comment]
Hi @lochness42 - what version of React Native are you using?

**Comment by lochness42** [comment]
0.61.4

**Comment by jmtaber129** [comment]
Hi @lochness42, I think I have an idea of what's breaking here.  Can you confirm that you are _not_ using the `Heap.withReactNavigationAutotrack()` higher-order component?

**Comment by lochness42** [comment]
Hi @jmtaber129 no I don't use `Heap.withReactNavigationAutotrack()` also we're using `react-native-router-flux` instead of `react-navigation`. If that's helpful or not.

**Comment by jmtaber129** [comment]
A fix has been merged, and will be included in version 0.9.1
