### ISSUE TITLE
Duplicate Modules in Android Project Structure

### ISSUE THREAD

**Issue by bsbechtel** [heap/react-native-heap#175]
When I try to build using Android Studio, I'm seeing the following issue:

```
ERROR: The modules ['@heap_react-native-heap', 'react-native-heap'] point to the same directory in the file system.
Each module must have a unique path.
```

I've tried cleaning my android project and cache, deleting and reinstalling node_modules, deleting my iml file, and nothing has worked. I'm on react-native 0.61.5 and react-native-heap 0.9.1

**Comment by jmtaber129** [comment]
Hi @bsbechtel!  I haven't been able to reproduce your issue, but a possible reason this is happening is that you've done some combination of performing `react-native link "@heap/react-native-heap"`, manually implementing the changes in our [install instructions](https://docs.heap.io/docs/react-native#section-android), and/or autolinking.

Check that only one of `'react-native-heap'` and `'@heap_react-native-heap'` in your `settings.gradle` and `app/build.gradle`.  If you're using autolinking, it's likely that neither of these should be in `settings.gradle` or `app/build.gradle`.

If these suggestions don't resolve the issue, the following information would help us debug this issue:
* The full log output of running `./gradlew clean :app:installDebug --refresh-dependencies` from the `android` directory of your project
* Any information related to dependency upgrades in your app (e.g. upgrading from an older version of RN to 0.61.5, upgrading to react-native-heap 0.9.1, etc.)
* Your `settings.gradle`, `app/build.gradle`, and `build.gradle`, and `app/src/main/java/com/rnheaptest/MainApplication.java` files.

**Comment by bsbechtel** [comment]
Hi @jmtaber129 I ended up uninstalling the module and completely re-installing it, and things seem to be working now. I think it had to do with the combination of manually implementing an installation, upgrading, and then react native autolinking the library. Thanks for the tips though and hopefully they help someone else seeing this issue!
