### ISSUE TITLE
react-navigation v5 issue (@react-navigation/native)

### ISSUE THREAD

**Issue by dhorobzieiev** [heap/react-native-heap#203]
Hi, 
Does your plugin support `@react-navigation/native` (v5.1.4)? 
I always receive an issue `The Heap library has crashed with an exception. ` - 'Cannot read property 'nav' of undefined' or 'Cannot read property 'nav' of null'. 
I am using @react-navigation/native v5 and was trying to implement it in two ways
1. 
`const Navigator = Heap.withReactNavigationAutotrack(NavigationContainer);
return (
    <Provider store={store.store}>
      <PersistGate loading={null} persistor={store.persistor}>
        <Navigator>
          <StatusBar />
          <BackButtonAction />
          <RootContainer />
        </Navigator>
      </PersistGate>
    </Provider>
  );`
2. 
const AuthStack = createStackNavigator();

class AuthContainer extends Component<Object, Object> {
  render() {
    return (
      <AuthStack.Navigator initialRouteName="SignInScreen">
        <AuthStack.Screen
          name="SignInScreen"
          component={SignInScreen}
          options={{headerShown: false}}
        />
        <AuthStack.Screen
          name="ResetPasswordScreen"
          component={ResetPasswordScreen}
          options={{headerShown: false}}
        />
        <AuthStack.Screen
          name="VerifyCode"
          component={VerifyCode}
          options={{headerShown: false}}
        />
        <AuthStack.Screen
          name="VerifyRecoveryCode"
          component={VerifyRecoveryCode}
          options={{headerShown: false}}
        />
      </AuthStack.Navigator>
    );
  }
}

export default Heap.withReactNavigationAutotrack(AuthContainer);

In both cases, I am getting an error.

**Comment by jmtaber129** [comment]
`react-native-heap`'s `withReactNavigationAutotrack` HOC does not currently support React Navigation 5+ due to a breaking API change with that version.  We do plan to support React Navigation 5 at some point, but we don't currently have a timeline for when this will happen.

For a workaround in the mean time, you can track screenviews on React Navigation 5 via `Heap.track` by implementing the code found at https://reactnavigation.org/docs/screen-tracking/.  This would automatically capture each screenview in your application as a custom event

**Comment by dhorobzieiev** [comment]
@jmtaber129 Thank you very much. It is very helpful link.

**Comment by BRL4528** [comment]
@jmtaber129 thanks, this link solved my problems

**Comment by jmtaber129** [comment]
Heap autocapture support for React Navigation 5 has been released as of `react-native-heap@0.13.0`.  Please upgrade to the latest version, and follow the instructions for integrating Heap with React Navigation to capture screenviews as first-class built-in autocaptured events (see https://developers.heap.io/docs/react-native#installation)
