### ISSUE TITLE
React 17 is not supported

### ISSUE THREAD

**Issue by wilsontr** [heap/react-native-heap#241]
`js/autotrack/common.ts` refers to `componentThis._reactInternalFiber` in several places. `_reactInternalFiber` has been renamed to `_reactInternals` in React 17. This causes Heap to throw an exception:

```The Heap library has crashed with an exception. {"message": "Pre-fiber React versions (React 16) are currently not supported by Heap autotrack.", "name": "Error", "stack": "Error: Pre-fiber React versions (React 16) are currently not supported by Heap autotrack.```

Example: 

```
const getComponentHierarchyTraversal: (
  comp: Component
) => ComponentHierarchyTraversalElement[] = componentThis => {
  // :TODO: (jmtaber129): Remove this if/when we support pre-fiber React.
  if (!componentThis._reactInternalFiber) {
    throw new Error(
      'Pre-fiber React versions (React 16) are currently not supported by Heap autotrack.'
    );
  }
```

**Comment by matt-oakes** [comment]
Opened a PR at #251

**Comment by walterholohan** [comment]
Same issue on our app after upgrading RN to 0.64.1. How do we your PR merged and released?

**Comment by andrea-11fs** [comment]
Same here , any ETA to get that PR merged ?
