### ISSUE TITLE
Identify and addUserProperties methods does not working

### ISSUE THREAD

**Issue by slava-the-skills** [heap/react-native-heap#259]
Environment:
```
...
"react-native": "0.64.2",
"@heap/react-native-heap": "^0.17.0-alpha1",
...
```

Code:
```
const { data: userSettings } = await axios.get(USER_SETTINGS_ENDPOINT);
      Heap.track('Set email', { email: userSettings.email });
      Heap.identify(userSettings.email);
      Heap.addUserProperties({
        email: userSettings.email,
});
```

Manual track event is working correctly, email is not empty. But on the Heap dashboard I don't see meta data with email by identify and add user property. Only on the 'Set email' event.

Same behavior with manual init and automatic initialization.

**Comment by mreilly-lula** [comment]
I'm experiencing this same issue with react native 63

**Comment by slava-the-skills** [comment]
> I'm experiencing this same issue with react native 63

Seems it's related with native SDK, I upgraded Heap SDK for IOS from `7.5.0` to `7.5.1` and seems now it's working correctly.

**Comment by mreilly-lula** [comment]
> > I'm experiencing this same issue with react native 63
> 
> Seems it's related with native SDK, I upgraded Heap SDK for IOS from `7.5.0` to `7.5.1` and seems now it's working correctly.

How did you upgrade to `7.5.1`?

**Comment by bnickel** [comment]
Version 0.17.0 of the SDK now ships with heap-ios-sdk 8.0.0+, which should resolve this issue if 7.5.1 was.  I'm going to close this issue, but please reopen if it is not resolved.
