### ISSUE TITLE
[IOS] Autocapture is not working on ios but works fine on android

### ISSUE THREAD

**Issue by jonaustin09** [heap/react-native-heap#272]
I followed the heap documentation and implement all steps but still I am facing issue that heap analytics shows nothing when I run my app on ios but works fine on android any help I am using react navigation 5

**Comment by MudassarSharifSandhu** [comment]
I am facing the same issue. It works in android but not on ios.
In the Live mode there is no data from the IOS platform.

**Comment by abriandev** [comment]
@MudassarSharifSandhu  did you find solution?

**Comment by bnickel** [comment]
This is an embarrassing mistake on my end.  I broke logging to production by implementing some test functionality.  There's a fix incoming, but a temporary workaround is to add an explicit URL to heap.config.json:

```json
{
    "default": {
      "heapAutoInit": true,
      "captureBaseUrl": "https://heapanalytics.com"
    },
    ...
}
```

**Comment by MudassarSharifSandhu** [comment]
Hi @bnickel ,
After adding `"captureBaseUrl": "https://heapanalytics.com"` to heap.config.json under all envirnments like default, dev and prod. It still is not capturing events.

**Comment by abriandev** [comment]
![simulator_screenshot_A111A183-4FE6-4F6D-8FE3-2DFBF73AA00F](https://user-images.githubusercontent.com/62040422/144313754-a30b7c47-38f2-4191-aaf2-b1a41b8064b3.png)
@bnickel  check this happens now my code is not working

**Comment by bnickel** [comment]
@MudassarSharifSandhu You'll need to rebuild if you haven't already.  The heap.config.json file gets built into the app as part of the iOS build process.

@abriandev Can you try rebuilding your app as well?  Heap doesn't use react-native-get-random-values so I'm not sure where that error would be coming from.

**Comment by abriandev** [comment]
@bnickel  I already rebuild the project 3 times but still see this error but on android app run fine but now on android its not showing live changes on heap analytics does this line  "captureBaseUrl": "https://heapanalytics.com" have any impact on android?

**Comment by abriandev** [comment]
@bnickel  I recheck it it works on android but on ios still got the error that i mentioned above

**Comment by abriandev** [comment]
@bnickel  should I add some thing in pod file for ios?

**Comment by bnickel** [comment]
@abriandev You may try running `pod install` in the ios directory to see if that does anything.

Android and iOS both consume the config file through build processes and native code, so the config change shouldn't impact JavaScript on either platform.  I'm going to push a fix so you can revert the config change an try out 0.17.1 when it ships.

**Comment by facundocastello** [comment]
I've the same error and also I've this on xcode output:

```
boringssl_metrics_log_metric_block_invoke(144) Failed to log metrics
2021-12-02 15:35:56.016852-0300 appname[25219:326979] [connection]
```
