### ISSUE TITLE
ios achieve failed - App not contain bitcode

### ISSUE THREAD

**Issue by elirangoshen** [heap/react-native-heap#343]
Hi,
When Im achieve my app, I'm getting that error on Heap: "/Heap/Heap.framework/Heap does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target."

I can disable my bitcode in xcode  but as it will affect my app I wonder if you aware of its and intend to use bitcode for heap ? 
I also didn't see anything in documentation 

heap version: 0.22.0 
react-native version: 0.69.4

**Comment by jerryhjones** [comment]
Hey @elirangoshen thanks for dropping a note.

As of Xcode 14, Apple has [deprecated Bitcode](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes#Deprecations), and it is stripped before submitting to the app store.

For this reason, we recommend disabling bitcode for your app. I will ask our team to update our docs to make this clearer.

More info here:
https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes#Deprecations
https://arbyswift.com/why-does-xcode-14-deprecate-bitcode
