### ISSUE TITLE
The Heap library has crashed with an exception

### ISSUE THREAD

**Issue by twistdmnd** [heap/react-native-heap#366]
Our application is built on top of firebase and some of the subscriptions can cause the Navigation stack to redraw. When it happens we may receive undefined in the onStateChange event of react-navigation. That seems properly handled in react-navigation v5. However, the heap navigation wrapper layer crashes in 
NavigationUtil.getActiveRouteNames, as the navigationState is undefined.

callstack of the error:
```
WARN  The Heap library has crashed with an exception. {"message": "Cannot read property 'routes' of undefined", "name": "TypeError", "stack": "TypeError: Cannot read property 'routes' of undefined
    at getActiveRouteNames (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=(hidden)&modulesOnly=false&runModule=true:83071:36)
```

**Comment by Clayton-notronixx** [comment]
We're also getting this with react-navigation v6 - can't seem to see a solution online anywhere

**Comment by Jas57** [comment]
Hi, has anyone found a solution to this? We're trying to integrate Heap into our application using v6 and getting the same issue. Thanks.

**Comment by TuurDutoit** [comment]
We are seeing a very similar issue upgrading to v6. We log one event very early on (with `Heap.track`), before the navigator is properly initialized. Therefore, react-navigation's `getRootState()` returns `undefined` (as documented [here](https://reactnavigation.org/docs/navigation-container/#getrootstate) and [here](https://reactnavigation.org/docs/navigating-without-navigation-prop/#handling-initialization)!), which throws an error in Heap's `getActiveRouteNames`
