### ISSUE TITLE
Did the way sessions are tracked change after 0.20.0?

### ISSUE THREAD

**Issue by alexbelyeu** [heap/react-native-heap#372]
We have an app that has had pretty consistent metrics since September. On December 14th we had a new release, which included a version bump of this library from 0.20 to 0.22. We don't deep link into the app, so all users land on the same screen when they log into the app. So this chart is tracking:
- Sessions, as measured by: Total events > Sessions
- Total views of main screen, as measured by: Total events > Views of the main screen
- Unique users that viewed the main screen, as measured by: Unique users > Views of the main screen

As you can see in the chart, the Sessions significantly dip after users adopted the new release but the events that track views of the main screen remain steady or even grow, which also tracks with other internal metrics that we have.

What could be going on?

![image](https://user-images.githubusercontent.com/12485062/223175574-0cf28e4e-639c-40d2-bebb-2389c713dafd.png)

**Comment by tejgokhale** [comment]
@alexbelyeu Can you link me to this chart? I'm finding a consistent view of sessions when I pull this myself in Heap.

**Comment by alexbelyeu** [comment]
Hey, Heap support got back to us and indeed the way unidentified sessions are triggered changed across these versions. Here is their explanation below:

> Without access to your app's code repository, this part is informed guesswork. But given the change in Heap.resetIdentity() behavior between the two versions of the iOS SDK, the most likely reason that the number of unidentified sessions was so much higher before the update is that resetIdentity() was being called on the login screen and/or other pages as-yet-unidentified users can access. Because under the SDK in use at the time, this caused the user ID to be regenerated and a new session to be triggered, this resulted in a very high volume of new unidentified sessions, most likely each with only a small number of events.
