### ISSUE TITLE
Cocoapods generates a new checksum on every `pod install`

### ISSUE THREAD

**Issue by guy-shahine** [heap/react-native-heap#400]
Using the same npm version of react-native-heap package, every time we run `pod install` a new checksum is generated. This behavior is odd and causing our CI machines to raise alerts because it's detected new changes in lock files.  Do we know the reason for this issue that does not happen with other packages we use? Thank you

**Comment by dauby88** [comment]
We have the same issue. I suspect it's the same issue that's resolved here: https://github.com/facebook/react-native/issues/31121#issuecomment-802182459
