### ISSUE TITLE
[Synk] Security vulnerability in dependency package babel-traverse

### ISSUE THREAD

**Issue by stevebtw** [heap/react-native-heap#420]
### Issue

See https://security.snyk.io/vuln/SNYK-JS-BABELTRAVERSE-5962463

Introduced through: `@heap/react-native-heap@0.22.6` › `babel-template@6.26.0` › `babel-traverse@6.26.0`

**Comment by msheahen** [comment]
seconding this.  this library now has a critical vulnerability.  seems its fixable by upgrading the version of babel/template.

**Comment by bomjkolyadun** [comment]
We also see this issue in our project.

**Comment by bnickel** [comment]
This is resolved in 0.22.7.  The dependency was mistakenly included for the babel plugin, while babel plugins don't actually declare dependencies on babel.
