### ISSUE TITLE
withReactNavigationAutotrack doesn't accept any props

### ISSUE THREAD

**Issue by potatopotaro** [heap/react-native-heap#91]
I noticed `withReactNavigationAutotrack` isn't allowing me to pass in any props, e.g. `screenProps`.

The code for `withReactNavigationAutotrack` doesn't render the app container with any way to include props, e.g. `<AppContainer {...props} />`.

**Comment by jmtaber129** [comment]
Thanks for catching this! The fix has been merged, and will be included in the next release
